[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "netlify/functions"


环境变量配置（在Netlify控制台中设置）
AI_API_URL = https://api.siliconflow.cn/v1
AI_API_KEY = sk-cfphdryhsemmjylqzrertjgdcvkymukqkkngiurwmapovzqp
AI_MODEL = Qwen/Qwen3-8B
ADMIN_USER = adminfishcat9898
ADMIN_PASSWORD = xx1465120
EXTRA_ADMIN_USER = auser
EXTRA_ADMIN_PASSWORD = apassword
API_TIMEOUT = 60